server:
  port: 8000

#logging.level.org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE


---

spring:
  profiles: prod
  datasource:
    password: 2vMNPU49Ep47HtYn
    username: afiyyet
    url: jdbc:postgresql://afiyyet.com:5432/afiyyet
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

sftp:
  host: https://afiyyet.com
  port: 2222
  user: smartmenu
  password: smartmenu
  remote:
    directory:
      upload: cdn/
  local:
    directory:
      upload: /tmp/afiyyet/cdn/


mail:
  host: smtp.gmail.com
  protocol: smtp
  port: 587
  username: aaaaaaa
  password: aaaaaaa
  debug: true
  smtp:
    auth: true
    starttls:
      enabled: true

app:
  baseCdnUrl: https://afiyyet.com:8002/
---

spring:
  profiles: test
  datasource:
    password: jw8s0F4
    username: smartmenu
    url: jdbc:postgresql://127.0.0.1:5432/smartmenu
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

sftp:
  host: 31.220.55.12
  port: 2222
  user: smartmenu
  password: smartmenu
  remote:
    directory:
      upload: cdn/
      download: ~/
  local:
    directory:
      download: /Downloads/
      upload: /smartmenu/cdn/


mail:
  host: smtp.gmail.com
  protocol: smtp
  port: 587
  username: aaaaaaa
  password: aaaaaaa
  debug: true
  smtp:
    auth: true
    starttls:
      enabled: true

app:
  baseCdnUrl: http://31.220.55.12:8002/
---

spring:
  profiles: dev
  datasource:
    password: 2vMNPU49Ep47HtYn
    username: afiyyet
    url: jdbc:postgresql://localhost:5432/afiyyet
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

sftp:
  host: localhost
  port: 2222
  user: afiyyet
  password: afiyyet
  remote:
    directory:
      upload: cdn/
  local:
    directory:
      upload: C:/Users/pc/Desktop/Works/afiyyet/cdn/



mail:
  host: smtp.gmail.com
  protocol: smtp
  port: 587
  username: aaaaaaa
  password: aaaaaaa
  debug: true
  smtp:
    auth: true
    starttls:
      enabled: true

app:
  baseCdnUrl: http://localhost:8002/