server:
  port: 8000

#logging.level.org.hibernate:
#    SQL: DEBUG
#    type.descriptor.sql.BasicBinder: TRACE

app:
  baseCdnUrl: https://afiyyet.com:5002/

spring:
  datasource:
    password: jw8s0F4
    username: smartmenu
    url: jdbc:postgresql://31.220.55.12:5432/smartmenu
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

sftp:
  host: https://afiyyet.com
  port: 2222
  user: smartmenu
  password: smartmenu
  remote:
    directory:
      upload: cdn/
      download: ~/
  local:
    directory:
      download: /Downloads/
      upload: /home/afiyyet/smartmenu/cdn/


mail:
  host: smtp.gmail.com
  protocol: smtp
  port: 587
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  debug: true
  smtp:
    auth: true
    starttls:
      enabled: true
---

spring:
  profiles: ilyas
  datasource:
    password: andrimbavy123
    username: postgres
    url: jdbc:postgresql://localhost:5432/smartmenu
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

sftp:
  host: localhost
  port: 2222
  user: smartmenu
  password: smartmenu
  remote:
    directory:
      upload: cdn/
      download: ~/
  local:
    directory:
      download: /Users/ilyas/Downloads/
      upload: /Users/ilyas/Desktop/projects/smartmenu/cdn/

app:
  baseCdnUrl: http://localhost:5000/